### ISSUE TITLE
Set up Kanban Board for Space Traveller's Project

### ISSUE THREAD

**Issue by lucy-sees** [lucy-sees/Space-Travellers-Hub#4]
### We are a group of two coding partners:

- @siddghosh108 
- @lucy-sees 

Link to our project: https://github.com/users/lucy-sees/projects/1

**Comment by tugsem** [comment]
##  STATUS: REQUIRED CHANGES ♻️
Hello team👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️the kanban board is created
✔️professional documentation
## Required Changes ♻️

- [x] Please add the column 'In Review' to match the given board.
![image](https://github.com/lucy-sees/Space-Travellers-Hub/assets/91486791/b2152822-0294-41be-b98b-65b7e01d2967)
![image](https://github.com/lucy-sees/Space-Travellers-Hub/assets/91486791/94f33967-c796-46f6-ae31-b84e288befd6)

- [x] Please check if you added all the cards for a team of 2. As per the requirement, there must be 17 cards, however your backlog shows 16.
- [x] @lucy-sees Please add one more card for the 'filters' task as per the requirement. @siddghosh108 has 2 'filters' but you should divide the categories equally.
![image](https://github.com/lucy-sees/Space-Travellers-Hub/assets/91486791/60fc0bf5-44e9-4f10-9c11-6ee9f91efe52)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lucy-sees** [comment]
Hi @tugsem , thanks for the constructive review, I have made the changes requested

**Comment by Olamarx** [comment]
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights
- Good use of Kanban board ✔️

 ## Required Changes ♻️
_Check the comments under the review._
- [x] I can see that the cards are 24 in number, whereas as pointed by the previous reviewer, it should be 17 since you are 2 on this group, I will encourage you to check the tasks again for you not to be adding tasks belonging to 3 members.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lucy-sees** [comment]
Hi @Olamarx , I have made the change you have requested. Thanks for the review

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
